version: 2

jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: hseeberger/scala-sbt
    steps:
      - checkout
      - run:
          name: Run Build
          command: sbt compile
      - run:
          name: Run Tests
          command: sbt test
      - save_cache:
          key: parallel-url-search-{{ .Branch }}-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy"
